from .TTS_melo import MeloTTS
from .tone_color_converter_openvoice import OpenVoiceToneColorConverter
from .TTS_GPT_SoVITS import GPTSoVITS_TTS
from .tone_color_converter_GPT_SoVITS import SoVITSToneColorConverter